# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def main_pods
  pod 'Alamofire', '~> 4.7'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
end

target 'proto-xcode' do
  project 'proto-xcode.xcodeproj'
  use_frameworks!
  main_pods
  
  target 'proto-xcodeTests' do
    inherit! :search_paths
    main_pods
  end
  
  target 'proto-xcodeUITests' do
    inherit! :search_paths
    main_pods
  end
end
